### ISSUE TITLE
financing is still broken

### ISSUE THREAD

**Issue by Luceeiy** [qbcore-framework/qb-vehicleshop#101]
when the players finance a vehicle they can keep it but all of a sudden they disappear from the garage giving the same error with the playtime

**Comment by DanteRedrum** [comment]
@Luceeiy I'm curious to know if the player uses f8 quit to leave the server. To my understanding using f8 quit can cause an issue with financing. I believe it's because once the player quits, the server is unable to retrieve the players playtime.
