### ISSUE TITLE
no vehicles in the showroom 

### ISSUE THREAD

**Issue by gfrast** [qbcore-framework/qb-vehicleshop#102]
hello!

Can you help me?
I entered everything and found no errors, the console does not display any errors
![screen1](https://user-images.githubusercontent.com/95580565/148101175-df175c14-b54e-43b9-8953-8bbf898cf32e.png)
![screen2](https://user-images.githubusercontent.com/95580565/148101202-fb49edb6-e995-4876-974b-98933698b078.png)
![screen3](https://user-images.githubusercontent.com/95580565/148101220-b88c63e1-96fb-4fd1-95d7-f276b95934bf.png)
![screen4](https://user-images.githubusercontent.com/95580565/148101227-09369552-e382-4d2b-b20a-e010533a8df5.png)

**Comment by Demo4889** [comment]
Categories are different from your vehicleshop and vehicles.lua file... make sure they are the same
