### ISSUE TITLE
finance vehicle is sell on rv sales

### ISSUE THREAD

**Issue by krishnz12** [qbcore-framework/qb-vehicleshop#106]
When vehicle bought on finance but do not repay the finance that vehicle sell's  on rv sales then the finance goes zero please  add in rv sales 
this vehicle could not sell please repay the loan and come after.

**Comment by DanteRedrum** [comment]
this might need to be an issue in qb-vehiclesales that can be resolved by having the vehicle sale function check for an existing finance loan on the vehicle and then saying to repay the loan before selling.  It might be even more enhanced by allowing you to sell if the remaining finance amount is lower than the sale price then taking the existing loan amount from the sales price to repay the loan and giving you the difference or taking away the difference if it is higher than the sale price unless you don't have the money in the bank or cash to pay off the remainder then it will tell you to repay before selling.
