### ISSUE TITLE
attempt to index a nil value (global 'v')

### ISSUE THREAD

**Issue by bigramb0** [qbcore-framework/qb-vehicleshop#108]
![putty_6bH7d7HA1S](https://user-images.githubusercontent.com/84361647/148274907-bd06176e-794b-4484-8bc4-c792e3cfa5e4.png)

**Comment by GhzGarage** [comment]
Have you updated today?

**Comment by bigramb0** [comment]
Yes, latest update

**Comment by GhzGarage** [comment]
Line 39 does not have a “v” in it so I’m guessing not
