### ISSUE TITLE
Vehicles disappear sometimes from the showroom

### ISSUE THREAD

**Issue by Dallepower** [qbcore-framework/qb-vehicleshop#110]
Hello QB! 

I'm having some issues with the vehicleshop, it's 100% plug'n'play no editing, i can't reproduce it sadly, but sometimes, i can see the vehicles, but the other players cannot.. and sometimes they can, and i can't, what can the error be?

It doesn't come up with any errors in server log or f8 log

best regards

**Comment by Klay4** [comment]
+1

**Comment by whoops1e** [comment]
+1

**Comment by MaDHouSe79** [comment]
i have to restart the script to make it working again, but this is not a fix. i also have this issue with a lot of other players on my server..

**Comment by whoops1e** [comment]
+1

**Comment by MaDHouSe79** [comment]
I found my issue, i had a self created mod,  and this was the issue why the showroom does not load in. make sure that no global values in other mods are the same name, for local values i dont think it does not metter but with global values this can be an issue for the showroom if you use the same value names. and this whas my issue and now everting is working again.

**Comment by Klay4** [comment]
@MaDHouSe79 like which ones? All the variables in qb-vehicleshop are local

**Comment by MaDHouSe79** [comment]
welll my issue was in my own parking system. i disable it and the shop works again. so i think maby a value or a global table get changes, i have not find it which values it is. and even if its a local value, this values gan maby change by function outsite of the vehicleshop. i have to look for it. but like i said, on my server my parking system was the issue.
