### ISSUE TITLE
attemp to index a nil value (field '?')

### ISSUE THREAD

**Issue by vosscat** [qbcore-framework/qb-vehicleshop#120]
SCRIPT ERROR: @qb-vehicleshop/client.lua:190: attemp to index a nil value (field '?')
> onPointInOutCb <@qb-vehicleshop/client.lua:190>
> fn (@PolyZone/ComboZone.lua:272)

**Comment by SmithyPD** [comment]
have a look at the polyzone fix, changing nul to false.
