### ISSUE TITLE
Vehicles do not show up in Showroom.

### ISSUE THREAD

**Issue by FizzGamingJR** [qbcore-framework/qb-vehicleshop#123]
Hello,
Ever since I began a QB server I have been having issues with the vehicle shop, sometimes the cars within the shop (The ones which allow you to purchase vehicles) do not show, they either show for others, or do not show at all. When I restart the script or server, they are not guaranteed to come back. So it's ends up like mayhem restarting the server about 5 times trying to fix it. I saw there were multiple other issues regarding this but it involved people having resources I did not, or overall a completely different situation.

If anybody has an idea what causes this issue, I would very much appreciate it.

**Comment by DevDokus** [comment]
We have the same issue and we found the following. 

- Restarting vehicle shop will only work for a player if it is restarted via the client console. Restarting the plugin via the server 
console, the vehicles will not spawn for the players

- In the server file it is registering net events what normally only is used in the client files. Not sure how it QB is using it but it feels not right. to register a server event `RegisterServerEvent` should be used and not `RegisterNetEvent`

- Also what i notice is that the events are directly made into `RegisterNetEvent` but this should only register the event, not execute is?  Where is the `AddEventHandler('Event', function() end)` where the code normally belongs as well for the server as the client files. 

Normally this should bounce a load of errors in the console when a server or net event ain't registered correctly, but i see none. As soon the plugin is restarted within the game by one of the admins with ACE permissions, the cards spawn in for all players. But those players that already had cars visible, will now see multiple cars spawned into each other. 

So it feel like this plugin has multiple problems at the moment

**Comment by FizzGamingJR** [comment]
> 

Very strange, I have not encounted any issues regarding the rooftop menu or anything other than the vehicles loading in and restarting problems. The fact that nobody is able to get an answer baffles me. There are also a lack of vehicle shop scripts out there for QBus / QBCore so this is a script in which people are restricted to use. A nice message informing us that the dev(s) are aware of this and is trying to find a fix would be kindly appreciated but I can't seem to see anything relating to this. The script was last updated 7 days ago in which an addition was made to the README.
This script is fantastic when it works the right way, but the problems make me want to remove it and keep it off my server.

Thank you for sharing your problems, I am sure the developers and or somebody out there will find a fix very soon (fingers crossed anyways.)

Have a good one, and stay safe.

**Comment by DevDokus** [comment]
haha yeah I found it strange also, but this I also had some times in RedM development. Its when a entity is spawned in on a certain height, whilst the player is still to far away, it does not place the entity on the ground properly, same with Uis. I hope they find a fix for this soon though, the car dealer is one of the most important plugins on a FiveM server haha.  The special car dealer for imports has the same issue also as described here. 

Patiently waiting if QB comes with a patch for this,  in the mean time writing a small quick plugin for the car shop ^^ 
A Fivem server can't live without one, its always all about the cars with those peeps :P

**Comment by ZacharySeebeck2020** [comment]
Has there been any update in regard to this issue? We're trying to launch a server a really need some sort of vehicle shop working. If not, is there a possibility of another plugin we could use to accomplish the same outcome as this tries to provide.

**Comment by FizzGamingJR** [comment]
> Has there been any update in regard to this issue? We're trying to launch a server a really need some sort of vehicle shop working. If not, is there a possibility of another plugin we could use to accomplish the same outcome as this tries to provide.

Still no update, nor any reply regarding this issue. I, myself am also looking for another script as a replacement. I have lost a fair few members, and angered a few due to this bug and it’s really starting to get on my nerves.

The only replacements I have see are paid scripts by popular authors, I won’t link or mention their names specifically but if you do a search a few options in which I have yet to test out will appear.

**Comment by DevDokus** [comment]
I am using now a different vehicle shop. If I am right, it is not made by QBus but made to work with QBus. You do need to change the code here and there a bit though. Also it uses a different database table for the vehicles, and you need to change how it grabs the user information, as this plugin belongs to a old server that I had. 

Hope it will help you guys in the mean time, losing player ain't fun. 
https://drive.google.com/file/d/1FXlOj2lqTbgyBZxNz-CWX3tp_K_8-jzY/view?usp=sharing
