### ISSUE TITLE
transfervehicle command

### ISSUE THREAD

**Issue by elmschaym** [qbcore-framework/qb-vehicleshop#129]
transfervehicle command is not working
 i have this message 

[script:qb-vehiclesho] SCRIPT ERROR: @qb-vehicleshop/server.lua:442: attempt to call a nil value (field 'GetPlate')
[script:qb-vehiclesho] > handler (@qb-core/server/events.lua:31)
[      script:qb-core] SCRIPT ERROR: error object is not a string

**Comment by SmithyPD** [comment]
yes we have the same error, line 442

**Comment by TheHorizon-Fivem** [comment]
ther is already a fix for this issue here
https://github.com/qbcore-framework/qb-vehicleshop/pull/131/commits
