### ISSUE TITLE
Vehicles change in other shops

### ISSUE THREAD

**Issue by SmithyPD** [qbcore-framework/qb-vehicleshop#130]
Ok so you will only see this if 2 people are in separate dealerships inside the polyzones.. 
If someone changes vehicles at pdm or luxury etc then the other person will see that vehicle appear in the dealership they are in as well.. so it changes in both. but you only see this if you are inside the polyzone.

**Comment by adweex** [comment]
I can confirm this bug. Added more than 5 shops, and if anyone is inside two separate shops, then the cars change like they are synced.

**Comment by buntyverma69** [comment]
check my pull requests I fixed that thing
