### ISSUE TITLE
"Vehicle Options" menu dissappears after being forced out of a test drive.

### ISSUE THREAD

**Issue by GHubbersz** [qbcore-framework/qb-vehicleshop#133]
https://medal.tv/games/gta-v/clips/be6JYdE_afwuU/d1337S0jveGM?invite=cr-MSxpaEcsMjc5MzQ0Mzcs

In the above video you can see when you take a vehicle out for a test drive and get kicked from the vehicle, you no longer have a menu. How can I fix this??

**Comment by Shotgunner187** [comment]
Same in my city!

**Comment by xoomer** [comment]
i am also having same issue

**Comment by FjamZoo** [comment]
This can only be nil if you are using an outdated version of PolyZone as it was fixed to only return true or false. 

please update or change this varaible https://github.com/mkafrin/PolyZone/commit/9ae6d417803cd1eda5f91500ba42aabf3340ee79
