### ISSUE TITLE
add new car 

### ISSUE THREAD

**Issue by tyler4435** [qbcore-framework/qb-vehicleshop#136]
how to add a add on car at simons

**Comment by AG-Monster** [comment]
> how to add a add on car at simons

Hi do you have discord I can help you out :)

**Comment by Estrix11** [comment]
I have the same question, can you help me as well please ?

**Comment by AG-Monster** [comment]
Sure DM me on AG-Monster#5544 I can help you out

**Comment by AG-Monster** [comment]
> I have the same question, can you help me as well please ?

Sorry my dms was closed you can add me now its open :)

**Comment by UNKNOWNSCOTSMAN** [comment]
hi. anychance you can help me out ? AG-Monster?

**Comment by AG-Monster** [comment]
> hi. anychance you can help me out ? AG-Monster?

Sure

**Comment by Obo32563** [comment]
qb-core/shared/vehicles.lua you can either add more or replace current ones.

**Comment by AG-Monster** [comment]
> qb-core/shared/vehicles.lua you can either add more or replace current ones.

You can add your own cars, you can add me on discord I'll help you how to do it it's really easy to do

**Comment by AG-Monster** [comment]
> qb-core/shared/vehicles.lua you can either add more or replace current ones.

Drop me a friend request on discord we can talk on there
