### ISSUE TITLE
qb-vehicleshop/client.lua:107:attempt tp a nil value (field '?') : Help me :(

### ISSUE THREAD

**Issue by Thomasbutler01** [qbcore-framework/qb-vehicleshop#142]
What dose this mean
script:qb-vehicleshop SCRIPT ERROR: @qb-vehicleshop/client.lua:107: attempt to index a nil value (field "?')
script:qb-vehicleshop > getVehBrand (@qb-vehicleshop/client. lua:107)
script:qb-vehicleshop> fn (@qb-vehicleshop/client. lua:303)

**Comment by Etcurate** [comment]
same

**Comment by SlimChances** [comment]
same

**Comment by Shabad0** [comment]
Did you ever get this figured out?

**Comment by SlimChances** [comment]
So far.  No.
