### ISSUE TITLE
using new .sql

### ISSUE THREAD

**Issue by GeekHamza1** [qbcore-framework/qb-vehicleshop#147]
i get this error when  apply new vehicleshop,sql update
![unknown (3)](https://user-images.githubusercontent.com/80644047/158082289-eda5ce55-3827-4fb9-ba04-c392bd9f99f6.png)

**Comment by GhzGarage** [comment]
Did you ever solve this?

**Comment by GeekHamza1** [comment]
> Did you ever solve this?

i moved to linux  and resolved the issue
