### ISSUE TITLE
Car Dealer

### ISSUE THREAD

**Issue by Dizzy92** [qbcore-framework/qb-vehicleshop#148]
So me and anther car dealer try to click on the car option in the show room to swap cars to sale but the after clicking on it, it just disappears, we had another admin do it and it works just find for him, any help would be appreciated!!

**Comment by BRODZ1Y61** [comment]
I seem to have the same issue

**Comment by Dizzy92** [comment]
I should've corrected this, but one thing we did was go outside of the building and came back in and was able to use the swap cars out, if that doesn't work then go to pdm and swap out a car, go back to the luxury pdm and you should have your menu to swap out cars

**Comment by GhzGarage** [comment]
Can you update your script and let me know if this is resolved?

**Comment by Dizzy92** [comment]
I'll talk to the owner and check that out but as of right now we have a new script for car dealerships
