### ISSUE TITLE
Exception When Viewing a Vehicle

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-vehicleshop#149]
I'm getting the exceptions shown below when I go up to a car on display and don't get the menu.

![image](https://user-images.githubusercontent.com/43043270/158894465-565eb1e7-31c0-4f20-80df-48f07948e37f.png)

**Comment by erikmeyer08** [comment]
![image](https://user-images.githubusercontent.com/43043270/158902038-ea24740e-c6a4-428e-9e22-a65e366bc790.png)

**Comment by SlimChances** [comment]
Im having the same issue

**Comment by GhzGarage** [comment]
Update your script and let me know if you still have this issue
