### ISSUE TITLE
Shop Menu Help Wanted

### ISSUE THREAD

**Issue by brynnie1** [qbcore-framework/qb-vehicleshop#152]
Im wondering if there is a way for anyone to be able to access the vehicle shop menu/ catalogue to look what cars are available, but not be able to buy, as a car dealer needs to sell them to only. As currently if a car dealer is on , no one can see what cars can be purchased.

**Comment by GhzGarage** [comment]
There are two types of shops, managed and unmanaged. The unmanaged allows anyone to interact with the vehicles regardless of the job

**Comment by brynnie1** [comment]
> There are two types of shops, managed and free-use. The free-use allows anyone to interact with the vehicles regardless of the job

Ok, are they still able to buy vehicles as I dont wany them to. I want car dealer only to sell but people to cycle through the cars available

**Comment by GhzGarage** [comment]
No they can't buy if it's managed and they don't have the job
