### ISSUE TITLE
Only PDM Works

### ISSUE THREAD

**Issue by GGCHades** [qbcore-framework/qb-vehicleshop#16]
Tested the 2nd vehicle shop as well as added a vehicle shop. You can not change the cars in game. 
Set up a police vehicle shop and placed one car for display. Attached it to the police job. You can purchase the display car but can't change to any other car through the menu. Tried both with the police job as well as false (no job required)

Went to the Luxury dealer (2nd dealership) and same issue. You can not change the vehicle. 

The only dealership where it is working is PDM. PDM works as intended.
No errors in F8 or server consol and i am using the newest QBCore and newest qb-vehicleshop. Database tables are as should be as well as shared.lua in QBCore is configured correctly. I have tried with the proper hash of the cars. Pushcasing the display car works and can be saved in garage. Just listing all the stelp for you so you know i have tried basically everything i can think of. 

Thank you

**Comment by pyire** [comment]
![image](https://user-images.githubusercontent.com/11545751/129420580-da2ee59b-2eb2-4921-a2d7-dedc6cbd189e.png)

Im also having issues with the latest version.    PDM is fine, but custom shops are not

**Comment by pyire** [comment]
for Import dealership:
Selecting a new car seems to hang-up the script somewhere:
The old car will disappear, and selected car will never show up.   No script errors....
Restarting QB-VehicleShop and trying it again actually pulled the new car up but then the script broke leaving this error:
![image](https://user-images.githubusercontent.com/11545751/129460961-e368d174-7a64-48fe-b785-a92e5ee04df9.png)

**Comment by BerkieBb** [comment]
> for Import dealership:
> Selecting a new car seems to hang-up the script somewhere:
> The old car will disappear, and selected car will never show up. No script errors....
> Restarting QB-VehicleShop and trying it again actually pulled the new car up but then the script broke leaving this error:
> ![image](https://user-images.githubusercontent.com/11545751/129460961-e368d174-7a64-48fe-b785-a92e5ee04df9.png)

That's your car not having a right name, works perfectly for me

**Comment by BerkieBb** [comment]
> Tested the 2nd vehicle shop as well as added a vehicle shop. You can not change the cars in game.
> Set up a police vehicle shop and placed one car for display. Attached it to the police job. You can purchase the display car but can't change to any other car through the menu. Tried both with the police job as well as false (no job required)
> 
> Went to the Luxury dealer (2nd dealership) and same issue. You can not change the vehicle.
> 
> The only dealership where it is working is PDM. PDM works as intended.
> No errors in F8 or server consol and i am using the newest QBCore and newest qb-vehicleshop. Database tables are as should be as well as shared.lua in QBCore is configured correctly. I have tried with the proper hash of the cars. Pushcasing the display car works and can be saved in garage. Just listing all the stelp for you so you know i have tried basically everything i can think of.
> 
> Thank you

Everything works, I just tested it, you do have to change the shop part in qb-core/shared.lua to the shopname in the config for the shop you want to add the car in to make the selecting of cars work.
