### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bobiii94** [qbcore-framework/qb-vehicleshop#168]
hello, 
it's been two days since I encounter this kind of error I can not find the source could you help me please

![Capture d’écran 2022-04-21 142737](https://user-images.githubusercontent.com/104144504/164457858-3e889fff-6dab-431e-a8a6-98e2a324f491.png)
e

**Comment by ic3d05** [comment]
have it too

**Comment by GhzGarage** [comment]
Can't replicate this isssue
