### ISSUE TITLE
SCRIPT ERROR: @qb-vehicleshop/server.lua:412: attempt to compare number with nil

### ISSUE THREAD

**Issue by pulsepk** [qbcore-framework/qb-vehicleshop#169]
Having this script issue on the console, when someone leaves the server, any fix?

**Comment by OMikkel** [comment]
Have you made any modifications to the server.lua file? 
Line 412 in qb-vehicleshop/server.lua is this `TriggerClientEvent('QBCore:Notify', src, 'This player is not close enough', 'error')` but it does not look like it is comparing any numbers

**Comment by GhzGarage** [comment]
Can't replicate this issue
