### ISSUE TITLE
[ISSUE] Cars randomly spawning in Vehicle Shop

### ISSUE THREAD

**Issue by W0lv3sxD** [qbcore-framework/qb-vehicleshop#170]
Hey, 

I have got the problem that random cars spawn in my vehicle shop. I cant find the line that spawns them. 

![image](https://user-images.githubusercontent.com/93610323/165800363-0a6b2132-96fc-472b-a820-208aca568c45.png)

I hope someone can help me.

Thanks in advance.

**Comment by Shotgunner187** [comment]
Anyone got the fix yet? Brand new latest QB template with nothing added to it  and still having this issue for me. Random ped car spawns in dealership

**Comment by LightUpFam** [comment]
I also get this often. I removed 3 of the 8 spawn points to help ease FPS for low tier systems. 
now i get random ped cars spawned in dealership

**Comment by LightUpFam** [comment]
![Uploading ped car.png…]()

**Comment by SmithyPD** [comment]
if its the same car, you can add its model and coords into qb-smallresources/client/removeentities.lua
and it will stop it from appearing there.

**Comment by GhzGarage** [comment]
Haven't been able to replicate this and it's an older issue so closing
