### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RichterTheReal** [qbcore-framework/qb-vehicleshop#173]
Helo Guys
i have an issue in the server.lua i have new downloadet the script but it does nothing 
the exact issue is:
SCRIPT ERROR: @qb-vehicleshop/server.lua:422: attempt to compare number with nil
https://prnt.sc/znLqU-nOIANT
this issue cums when i start the server and a player joins

srry for my english

**Comment by GhzGarage** [comment]
Re-download the script
