### ISSUE TITLE
[BUG] SCRIPT ERROR: @qb-vehicleshop/client.lua:180 attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by marquisbee** [qbcore-framework/qb-vehicleshop#177]
**Describe the bug**
When you test drive a vehicle and are brought back to the shop you can no longer access the vehicles until the script is restarted or the person relogs.

**To Reproduce**
1. Go to PDM
2. Test Drive any vehicle
3. Try to swap vehicles after you're brought back to the dealership

**Expected behavior**
We'd be able to swap vehicles or purchase vehicles after a test drive.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: This week
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? No

![image](https://user-images.githubusercontent.com/105036318/167689152-8481a1c7-0b91-4159-b880-90fa9ec081db.png)

**Comment by MissTitanK3** [comment]
I am having this issue as well.

**Comment by GhzGarage** [comment]
This should be fixed
