### ISSUE TITLE
[BUG] transfervehicle not updating player license

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-vehicleshop#180]
The /transfervehicle slash command is only updating the player citizenid and not updating the player license in the player_vehicles table.
This is causing major issues with the qb-garages script as it looks for both keys and is throwing both client and server side exceptions.
I had to go through my entire player_vehciles table and match up the player license with the player citizenid to correct the data issues.
@GhzGarage 

`MySQL.Async.execute('UPDATE player_vehicles SET citizenid = ? WHERE plate = ?', {targetcid, plate})`

![image](https://user-images.githubusercontent.com/43043270/168486552-09dda88e-c774-4ef4-948c-7fb7aac5b128.png)
![image](https://user-images.githubusercontent.com/43043270/168486564-1ab59af9-3a12-408e-a325-d2af42b96a5e.png)

**Comment by GhzGarage** [comment]
I'll test this
