### ISSUE TITLE
Issue luxury cars dont spawn 

### ISSUE THREAD

**Issue by Reidoly95** [qbcore-framework/qb-vehicleshop#181]
I am having an issue with luxury its set up by default like in the script. But no cars spawn in there and nothing for the car dealer job is it just me or is something not working..

**Comment by Reidoly95** [comment]
Like showroom cars dont appear nothing. Idk how to fix this

**Comment by LightUpFam** [comment]
make sure you set the shared lua info correctly. 

change PDM to Luxury 
also make sure its set to right category 
and that category is visible to that location

**Comment by GhzGarage** [comment]
Re-download the script and configure it. The cars spawn fine
