### ISSUE TITLE
latest release test drive spawn messed up[BUG]

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-vehicleshop#186]
Test drive makes car spawn right on top pf the purchased car...
had to DV car after.
test drive doesnt de-spwan car after either

**Comment by Belorico** [comment]
Thats because you the same coordinates for test drive and purchased vehicles... If more people test or buy vehicle, they will all spawn on top of each other.

Vehicles are despawning when testdrive ends.

**Comment by merpindia** [comment]
Check my PR

**Comment by GhzGarage** [comment]
This has been resolved
