### ISSUE TITLE
[BUG] Vehicles floating

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-vehicleshop#187]
on server restart, the cars for sale are floating in air 

fixes after restarting script

**Comment by LightUpFam** [comment]
Ive done this and it make the cars in the floor or floating on a server restart regardless of what the 3rd coord number it set to. 
a restart of script always seems to fix this

**Comment by TheGoatRico** [comment]
Same issue here

**Comment by FizzGamingJR** [comment]
> Ive done this and it make the cars in the floor or floating on a server restart regardless of what the 3rd coord number it set to. 
> 
> a restart of script always seems to fix this 
> 
> 

If they are in the floor this means that you have lowered the number down too much, you need to change it accordingly so it's steady on the floor.
It's awkward as you have to restart the server to actually see the changes take place.
Restarting the script will fix the issue, temporarily. After you restart the server it will float again unless you change the third number as I said.
I have done this on 3 vehicle shops and all of them are now on the floor even when I restart the script or server.

**Comment by Deadgaminglive** [comment]
happens to me also, and i cant lower the vehicles because my menus over the car dont work after every resart untill i reset the script, when i reset it puts cars on the floor and i can open all menus like normal...so if i lowered em it would put them in the floor when i reset,

**Comment by Borreke0** [comment]
You need to lower the Z (3rd) value until it reaches the floor.
Afterwards, you need to make sure your shapes are having the same value +- to make sure your menu's will work. :)

**Comment by GhzGarage** [comment]
This has to do with the distance from the shop you are on load, i'm working on a fix
