### ISSUE TITLE
[BUG] Attempt to call a nil value (upvalue 'GeneratePlate')

### ISSUE THREAD

**Issue by cezeulor** [qbcore-framework/qb-vehicleshop#195]
I would greatly appreciate if someone could help me with this problem

![error](https://user-images.githubusercontent.com/106556095/171274813-a3a24936-7099-41d8-8650-2b55ef8dac00.jpg)
![Code](https://user-images.githubusercontent.com/106556095/171274816-ac82a67b-88b4-40ef-983f-2c5c0304d7f8.PNG)
m

**Comment by GhzGarage** [comment]
Not even sure what this is because that code isn't in this resource
