### ISSUE TITLE
[BUG] Unlimited Test drive car's

### ISSUE THREAD

**Issue by milotiro95** [qbcore-framework/qb-vehicleshop#196]
**Describe the bug**
Just take a car to the vehicleshop for a test. Go out and tell a friend to enter into the car. When the timer is end the car isn't returning to the shop and the owner keep the keys. Just do it every time you logged in to get a lambo for free !

**Comment by GhzGarage** [comment]
Investigating this

**Comment by GhzGarage** [comment]
This is fixed
