### ISSUE TITLE
[BUG] Cars not loading in vehicleshops

### ISSUE THREAD

**Issue by SmithyPD** [qbcore-framework/qb-vehicleshop#197]
**Describe the bug**
sometimes the vehicles are not showing in all locations.. restarting the vehicleshop sometimes fixes it, or they will be in one shop and not others

**Expected behavior**
all shops should contain a load in vehicle

**Screenshots**
n/a

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? No

**Additional context**
Also whats with the config file and the commas at the end of each shop or vehicles? or even the zones?
The commas are inconsistent and dont follow any logical pattern between the shops.. 
The file just doesnt seem to flow, and is there a reason to it or is it a mistake?

**Comment by GhzGarage** [comment]
Can't replicate this issue

**Comment by JYNKZIE** [comment]
been having the issue as well. no errors.

**Comment by GhzGarage** [comment]
Invalid issue, user error
