### ISSUE TITLE
Bugged menu from model loading

### ISSUE THREAD

**Issue by 5m1Ly** [qbcore-framework/qb-vehicleshop#20]
When i walk away from the vehicle at the moment i changed the vehicle and it is telling me that the model is loading then the vehicle never spawns. When this happends and i try to reselect another vehicle then i'm able to open the menu with g when i'm in the menu i'm nog able to continu with my key board only with my mouse. At this point i'm in the catagorys section but i was not able to proceed from this point forward.

**Comment by gicon** [comment]
^^ can confirm.  Willing to bet you're trying to load tuner DLC vehicles and haven't enabled the tuner DLC.   Follow Cappinator's advice and you'll be good to go.

**Comment by 5m1Ly** [comment]
Is was loading the manana

**Comment by 5m1Ly** [comment]
And this isseu is not about the car not loading but about the menu being bugged from it

**Comment by 5m1Ly** [comment]
So if you dont want to have any dlc to be enabled just vanilla gta that the car dealer stil functions as aspected because that is the type of qwality you want to deliver to you customers as a developer

**Comment by GhzGarage** [comment]
There are no customers here
