### ISSUE TITLE
[BUG] Financing

### ISSUE THREAD

**Issue by OwenT1** [qbcore-framework/qb-vehicleshop#201]
Whenever someone finances a car the down payment gets taken but nothing else comes out of there account at all so there getting a free car and lots of people are starting to finance cars and then become rich off cars

**Comment by GhzGarage** [comment]
Only a down payment would come out when they first financed it, once the finance timer is up then it will prompt for payment and if they don't pay within the configured amount of time then the vehicle will be removed from them

**Comment by OwenT1** [comment]
This has never happened for me mate when I’ve financed a car I’ve kept it forever no money taken etc

**Comment by GhzGarage** [comment]
Then you've got something else going on

**Comment by LightUpFam** [comment]
same.  I just set finance to 99% so noone uses it as a way to get a free car.

**Comment by GhzGarage** [comment]
There’s nothing wrong with the resource. I use it on a live server with many players financing and the timer works as intended. No one “gets a free car”

**Comment by OwenT1** [comment]
Timer shows lol but doesn’t take any money from people I’ve seen it on multiple servers I’ve worked on
