### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ggoodell2** [qbcore-framework/qb-vehicleshop#202]
**Describe the bug**
Addon/no GTA vehicles do not work properly. Cannot buy them.

**To Reproduce**
1. Swap vehicle to on in addon or 1of1 category.
2. vehicle name at top of menu stays on last gta vehicle in that spot
3. can test drive selected addon/1of1 but cannot buy. when attempt to buy it buys gta vehicle from 2.
4. SCRIPT ERROR: @qb-vehicleshop/client.lua:101: attempt to index a lil value (field '?' first time that error has ever shown up.

**Expected behavior**
Expect to be able to buy selected non gta vehicle

**Screenshots**
https://gyazo.com/2896565cb046e7cd82cd480fa3b419b0

**Questions (please complete the following information):**
 - When you last updated: vehicleshop today. qb in general 7 days ago
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

**Additional context**
also after test drive the menu does not pop up even after walking away from vehicle.

**Comment by ggoodell2** [comment]
after test drive this shows up in f8 console https://gyazo.com/0a64bf6c8df42eba954fbc8105759f22

**Comment by GhzGarage** [comment]
You can buy addon vehicles perfectly fine if they are in your shared, my server has players purchasing them every day

**Comment by ggoodell2** [comment]
updated to current files and now as soon as i load in i get this. https://gyazo.com/7950c560b0993a51178b1e39b4b5575d

**Comment by JasonOVO** [comment]
I having same problem

**Comment by GhzGarage** [comment]
You updated wrong then because the function is right here https://github.com/qbcore-framework/qb-vehicleshop/blob/372e8cf7dcc6bf765c057cf52c639ed3fbd9f45e/client.lua#L345
