### ISSUE TITLE
[BUG] Vehicle Test Drive

### ISSUE THREAD

**Issue by LateNightRP** [qbcore-framework/qb-vehicleshop#205]
**Describe the bug**
PDM test drive works, but any other vehicle shops throw this error code when test driving a vehicle, boat or air vehicle shop.

**To Reproduce**
1. Go to a Boat, air or any non PDM shop.
2. Choose a vehicle to test drive.

**Screenshots**
(https://cdn.discordapp.com/attachments/956649776487751680/984201015869984858/218_20220608165910_1.png)

**Questions (please complete the following information):**
 - When you last updated: Today (6/8/22)
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? No

**Comment by LateNightRP** [comment]
Noticed if I add this code to all of the other vehicle shops (other then pdm that already has it) vehicle test drive works correctly. 

['TestDriveSpawn'] = vector4(-8.24, -1089.73, 26.69, 68.78),

**Comment by GhzGarage** [comment]
Yeah somehow that entry was missed in the others
