### ISSUE TITLE
[BUG]When selecting car i getting this

### ISSUE THREAD

**Issue by JasonOVO** [qbcore-framework/qb-vehicleshop#207]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the f
![Screenshot 2022-06-11 173039](https://user-images.githubusercontent.com/107092380/173174927-c29de376-e159-41ad-a324-56ceb392b07f.png)
![vehshop client 101](https://user-images.githubusercontent.com/107092380/173174929-1b59ad6c-ef0c-4da8-8779-1073c63e39b3.png)
eature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by GhzGarage** [comment]
Looks like the car probably isn’t in the shared

**Comment by JasonOVO** [comment]
I did put all the mod car in the shared files

**Comment by JasonOVO** [comment]
![image](https://user-images.githubusercontent.com/107092380/173381609-705cbb2c-306a-4fdf-be50-45dcdc39dcc2.png)

**Comment by JasonOVO** [comment]
![image](https://user-images.githubusercontent.com/107092380/173382641-133096f7-1745-4015-bc9a-074ffc92afd0.png)

**Comment by mjvanhaastert** [comment]
got fixed with the latest updated
https://github.com/qbcore-framework/qb-vehicleshop/commit/4792cf1c6ce522e286bb2100610e7f6e23e1ca59
