### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by RenggoStarz** [qbcore-framework/qb-vehicleshop#213]
any one know how to set custom no plate for player buy vehicle auto set.
example i set HK***KH

**Comment by GhzGarage** [comment]
You'd have to code in another box in qb-input to enter a plate

**Comment by RenggoStarz** [comment]
> You'd have to code in another box in qb-input to enter a plate

in qb-vehicleshop enter plate ? can teach me .. i dunno how to make this custom plate
