### ISSUE TITLE
[BUG] SCRIPT ERROR: qb-vehicleshop/client.lua:98: attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by JordanBScott** [qbcore-framework/qb-vehicleshop#217]
**Describe the bug**
When entering the area of a vehicleshop the error below comes up in my F8 console which results in the vehicleshop not working at all. It doesn't effect PDM, Luxury, or the shop at the fire department that I have. Just the 3 that I have at 3 police stations.

**To Reproduce**
1. Go to a vehicle shop (3 out of 5 in my server have this issue)
2. Once in the area of the vehicleshop, you get the error in the screenshot below.

**Expected behavior**
I am getting this error when walking up to 3 of the 6 vehicleshops I have in my server and it happens to be the 3 police dealerships I have at the police stations in Los Santos, Sandy, and LS Freeway. 

**Screenshots**
![Screenshot (455)](https://user-images.githubusercontent.com/99845881/177238155-cb73054e-3e7a-4af8-a8d2-409b1dcce2b7.png)

**Questions (please complete the following information):**
 - When did you last update? 3 days ago
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
None

**Comment by GhzGarage** [comment]
Make sure your police vehicles are added into your shared/vehicles.lua properly

**Comment by cmgjones** [comment]
Having the same issue here , Pops up also when trying to change a car to an addon within the menu it get locked to the base game car selected before. For example swap vehicle to golfgti it will load the vehicle but header and price reflect the previous gta car selected. Attached a copy of my shared lua. 
![image](https://user-images.githubusercontent.com/18008375/180962506-c9be37ee-98c4-410e-8927-3447adb4d764.png)
