### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JYNKZIE** [qbcore-framework/qb-vehicleshop#219]
**Describe the bug**
vehicles on showrooms appear for some players but not all.
some player experience no cars in the showrooms, while some players who loaded in the same time during same sessions, see the vehicles and can interact/buy

**Expected behavior**
some player experience no cars in the showrooms, while some players who loaded in the 

**Questions (please complete the following information):**
 - When you last updated: Sunday, July 10, 2022
 - Are you using custom resource? which ones? qb-target, which is updated to newest, and no updates from myself
 - Have you renamed `qb-` to something custom? no

**Comment by Tamer173** [comment]
Same problem here Both PDM and Luxuary vehicleshop Vehicles are not showing Please fix the issue ASAP.

**Comment by peppinoita** [comment]
Have you noticed if this issue happens when you logout from a character and login again with another or with the same?
I suspect there is nomething wrong with the logout/login feature and spawned entities

**Comment by JYNKZIE** [comment]
i havent noticed any pattern regard logouts or character changes, 

it comes and goes for people. sometimes a player will see them after a server restart, sometimes they cant.

**Comment by JYNKZIE** [comment]
been on going for a while and its been ignored before https://github.com/qbcore-framework/qb-vehicleshop/issues/197#issue-1258229478

**Comment by JYNKZIE** [comment]
after playing around with it. its not server based only client.

i installed a fresh copy of both the server and client today, simply added two tables and the end of the new client.lua of qb-vehicleshop;

```
CreateThread(function()
    for name, shop in pairs(Config.Shops) do
        if shop['Type'] == 'free-use' then
            createFreeUseShop(shop['Zone']['Shape'], name)
        elseif shop['Type'] == 'managed' then
            createManagedShop(shop['Zone']['Shape'], name)
        end
    end
end)

CreateThread(function()
    for k in pairs(Config.Shops) do
        for i = 1, #Config.Shops[k]['ShowroomVehicles'] do
            local model = GetHashKey(Config.Shops[k]["ShowroomVehicles"][i].defaultVehicle)
            RequestModel(model)
            while not HasModelLoaded(model) do
                Wait(0)
            end
            local veh = CreateVehicle(model, Config.Shops[k]["ShowroomVehicles"][i].coords.x, Config.Shops[k]["ShowroomVehicles"][i].coords.y, Config.Shops[k]["ShowroomVehicles"][i].coords.z, false, false)
            SetModelAsNoLongerNeeded(model)
            SetEntityAsMissionEntity(veh, true, true)
            SetVehicleOnGroundProperly(veh)
            SetEntityInvincible(veh, true)
            SetVehicleDirtLevel(veh, 0.0)
            SetVehicleDoorsLocked(veh, 3)
            SetEntityHeading(veh, Config.Shops[k]["ShowroomVehicles"][i].coords.w)
            FreezeEntityPosition(veh, true)
            SetVehicleNumberPlateText(veh, 'BUY ME')
        if Config.UsingTarget then createVehZones(shopName, veh) end
        end
    end
end)

```


i placed it at the end of the enter file, ive had no issues so far. i am waiting for player feedback on the issue. and ill report it and close this

**Comment by Jafool** [comment]
This resource is predicated on the "Los Santos Tuners" game build (2372).

Make sure you're enforcing that build in your server config.

`set sv_enforceGameBuild 2372`

As long as you're enforcing this build there shouldn't be a problem.
I'm guessing here but, it's likely the case that other game builds might have slightly different hashes/IDs for vehicles/objects or something similar. I've noticed issues with certain clothing/skins not acting properly on different game builds as well.

**Comment by JYNKZIE** [comment]
ye my above method wasnt effective. it would double the entities, likewise. 

i had my build to 'Contracts' so ill go back to Tuners and monitor it some more.
