### ISSUE TITLE
Some vehicles wont disappear when placed into a vehicleshop

### ISSUE THREAD

**Issue by ammopack** [qbcore-framework/qb-vehicleshop#22]
I put a shop in with emergency vehicles, and whenever they're selected they wont despawn for the next selection. Tested at multiple locations and fresh install. No errors. 
It seems there are multiple classes this happens in. Including trailers as well.
![what](https://user-images.githubusercontent.com/52944965/131598233-7b017cd4-6ff8-46e6-bb37-c783dd490e01.PNG)
![aslso](https://user-images.githubusercontent.com/52944965/132556806-09c8ef0c-be15-4439-8672-840add515012.PNG)

**Comment by GhzGarage** [comment]
Tested this and couldn't replicate
