### ISSUE TITLE
[BUG] qb-vehicleshop can't transfer vehicles

### ISSUE THREAD

**Issue by martink1337** [qbcore-framework/qb-vehicleshop#222]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Buy vehicle
2. Sell it to someone with /transfervehicle (/transfervehicle 3 100) (for example)
3. And the car is not on your garage or on the other player garage
4. In database citizenID instead of other player ID it shows "0"

**Expected behavior**
Expected - the car should go to other player garage and in the database CITIZENID should be other player's ID.

**Video**
Video (Showcase): https://youtu.be/GGgn_7BW5II

**Questions (please complete the following information):**
 - When you last updated: [today 7/17/2022]
 - Are you using custom resource? which ones? [no]
 - Have you renamed `qb-` to something custom? [/no]

**Comment by LukeeeChan** [comment]
Has there been a fix for this yet?

**Comment by mjvanhaastert** [comment]
it should be fixed with this pr  #228
