### ISSUE TITLE
qb vehicleshop spawn and finance menu[BUG]

### ISSUE THREAD

**Issue by silentsound1** [qbcore-framework/qb-vehicleshop#223]
**Describe the bug**
in vehicle shop when you buy a car it spawns 2 time outside and as well the finance menu does not work it does not open the options at all when you finance the car

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]  Now
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] qb target and vehiclecarkeys
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by Blooper-bloop** [comment]
> **Describe the bug** in vehicle shop when you buy a car it spawns 2 time outside and as well the finance menu does not work it does not open the options at all when you finance the car
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Use this item '....' (item's name from shared.lua if applicable)
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: [e.g. last week]  Now
> * Are you using custom resource? which ones? [e.g. zdiscord, qb-target] qb target and vehiclecarkeys
> * Have you renamed `qb-` to something custom? [e.g. yes/no] no

Has this issue been solved for you yet as we have done some updates with qb-vehicleshop :) @silentsound1

**Comment by Blooper-bloop** [comment]
We are going to close this if you need any help let me know #Blooper#7612 thats my discord @silentsound1
