### ISSUE TITLE
[BUG] Payments not automatically taking

### ISSUE THREAD

**Issue by AtlCanadianGG** [qbcore-framework/qb-vehicleshop#224]
Player vehicles are being removed from player_vehicles randomly, I can't tell if it's due to non payment or not - are payments automatic? I thought they were, but that's the only thing I can think of. Has happened to 3 different players so far.

**Comment by sinphoenix** [comment]
same issue here with no notification for pay or late payment

**Comment by AtlCanadianGG** [comment]
This should be fixed ASAP

**Comment by AtlCanadianGG** [comment]
Still have this bug

**Comment by Blooper-bloop** [comment]
> Player vehicles are being removed from player_vehicles randomly, I can't tell if it's due to non payment or not - are payments automatic? I thought they were, but that's the only thing I can think of. Has happened to 3 different players so far.

it seems your posting a lot of issues that we cant reproduce do you have any time to join in a discord call if so just give me a dm Blooper#7612 im always free :) @AtlCanadianGG
