### ISSUE TITLE
[BUG] Vehicles dont show up in Vehicle shop all the time

### ISSUE THREAD

**Issue by sinphoenix** [qbcore-framework/qb-vehicleshop#226]
**Describe the bug**
Vehicles will not show up on car lots for everyone. If you fly out and come back in they will show up. Started with lastest update of the script itself. This is a fresh build only 3 days old. 

**To Reproduce**
Happens randomly

**Expected behavior**
Vehicle shop car wont be there for everyone but if you fly out and back in.. they are there

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 3 days ago, fresh build
 - Are you using custom resource? zdiscord, CODE BLACK HUD, JIMS Mechanic, All of Jims Business 
 - Have you renamed `qb-` to something custom? no

**Additional context**
Other then that issue, Cars are being removed from database without warning or payment notifications.

**Comment by sinphoenix** [comment]
SCreen shot

https://i.imgur.com/L5TYKKB.jpeg

**Comment by OutragedMetro** [comment]
I am running into this same issue did you ever solve this?

> SCreen shot
> 
> https://i.imgur.com/L5TYKKB.jpeg

**Comment by sp19851** [comment]
+

**Comment by JustGeezyGames** [comment]
Same exact issue... happens randomly and I haven't been able to figure out what happens to prevent them from spawning.

**Comment by AscendoTuum86** [comment]
Seeing this as well, and restarting the script does not fix it. No errors in console or server. It's not just the vehicles though, I have seen the finance spot disappear on script restart at times, and other times vehicles won't show up, but the financing spot is there... it's very random.

**Comment by Blooper-bloop** [comment]
> **Describe the bug** Vehicles will not show up on car lots for everyone. If you fly out and come back in they will show up. Started with lastest update of the script itself. This is a fresh build only 3 days old.
> 
> **To Reproduce** Happens randomly
> 
> **Expected behavior** Vehicle shop car wont be there for everyone but if you fly out and back in.. they are there
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: 3 days ago, fresh build
> * Are you using custom resource? zdiscord, CODE BLACK HUD, JIMS Mechanic, All of Jims Business
> * Have you renamed `qb-` to something custom? no
> 
> **Additional context** Other then that issue, Cars are being removed from database without warning or payment notifications.

Hey Dose this still happen we have updated qb-vehicleshop just wanted to know if it still happens :) @sinphoenix

**Comment by JustGeezyGames** [comment]
> Hey Dose this still happen we have updated qb-vehicleshop just wanted to know if it still happens :) @sinphoenix

I believe I had all the updates in when I experienced this bug. Although, I don't believe I've seen it happen lately. I'll definitely stop by PDM more often to verify.

**Comment by Arcticguy867** [comment]
it happens but if  u do changes but if u clear cache it fixes it

**Comment by Irishstevie** [comment]
> **Describe the bug** Vehicles will not show up on car lots for everyone. If you fly out and come back in they will show up. Started with lastest update of the script itself. This is a fresh build only 3 days old.
> 
> **To Reproduce** Happens randomly
> 
> **Expected behavior** Vehicle shop car wont be there for everyone but if you fly out and back in.. they are there
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: 3 days ago, fresh build
> * Are you using custom resource? zdiscord, CODE BLACK HUD, JIMS Mechanic, All of Jims Business
> * Have you renamed `qb-` to something custom? no
> 
> **Additional context** Other then that issue, Cars are being removed from database without warning or payment notifications.

I have tried to recreate this issue but it seems that I can't. if you can give more details with any errors showing in the console and the steps taken to move to Gabz PDM :) <3
