### ISSUE TITLE
[BUG] Vehicle does not spawn after purchase!

### ISSUE THREAD

**Issue by FizzGamingJR** [qbcore-framework/qb-vehicleshop#229]
**Describe the bug**
Upon purchasing a vehicle, and the script taking the money of the person, the vehicle does not spawn or place itself inside a garage.
The purchased vehicle is added to the database, but is not to be found anywhere...

**To Reproduce**
1. Go to a vehicle shop.
2. Purchase a car
3. See problem.

**Expected behavior**
Vehicle is expected to spawn outside of the shop, allowing the person who purchased the car to drive it.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? No

**Additional context**
The script was working 2 days ago, but is now broken?

**Comment by GhzGarage** [comment]
Did you update the vehicle shop recently? If so you need to go get the callbacks in the core

**Comment by FizzGamingJR** [comment]
> Did you update the vehicle shop recently? If so you need to go get the callbacks in the core

Hello there, I recently updated the qb-vehicleshop script, should I update the qb-core framework as well? or are you telling me to do something different.

**Comment by FizzGamingJR** [comment]
> Did you update the vehicle shop recently? If so you need to go get the callbacks in the core

I have just now updated my qb-core, I apologise about the waste of time, should have really been my first thought when I had the issue.
Thank you for giving me support even though it was a stupid bug report lol, you have a great rest of your night!
