### ISSUE TITLE
[BUG] Test drive vehicle will not despawn if a different player touches car.

### ISSUE THREAD

**Issue by mclenz** [qbcore-framework/qb-vehicleshop#230]
**Describe the bug**
When test driving, if the player spawns a test drive vehicle, gets out, and another player attempts to get into the vehicle, the vehicle will not despawn at the end of the test drive timer.

**To Reproduce**
1. Go to dealership.
2. Player A spawns test drive car.
3. Player A gets out of the test drive car.
4. Player B attempts to enter the test drive car.
5. The test drive timer expires and the vehicle does not despawn.

**Expected behavior**
Expect the vehicle to despawn.

**Questions (please complete the following information):**
 - When you last updated: Last week (7/29 date on files).
 - Are you using custom resource? which ones? Nothing custom related to vehicle shop.
 - Have you renamed `qb-` to something custom? No

**Additional context**
If the original person is the only person to touch the vehicle, the vehicle respawns. Issue only seems to happen if another person tries to get into the vehicle.

**Comment by Blooper-bloop** [comment]
> **Describe the bug** When test driving, if the player spawns a test drive vehicle, gets out, and another player attempts to get into the vehicle, the vehicle will not despawn at the end of the test drive timer.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to dealership.
> 2. Player A spawns test drive car.
> 3. Player A gets out of the test drive car.
> 4. Player B attempts to enter the test drive car.
> 5. The test drive timer expires and the vehicle does not despawn.
> 
> **Expected behavior** Expect the vehicle to despawn.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: Last week (7/29 date on files).
> * Are you using custom resource? which ones? Nothing custom related to vehicle shop.
> * Have you renamed `qb-` to something custom? No
> 
> **Additional context** If the original person is the only person to touch the vehicle, the vehicle respawns. Issue only seems to happen if another person tries to get into the vehicle.

Is this still a problem just because it was 24 days ago @mclenz

**Comment by tom-osborne** [comment]
@Blooper-bloop can you test this with someone? Follow the steps provided

**Comment by Blooper-bloop** [comment]
> @Blooper-bloop can you test this with someone? Follow the steps provided

Will Do

**Comment by GhzGarage** [comment]
Fixed
