### ISSUE TITLE
[BUG] Purchasing Vehicle w/ Someone Nearby turns spawned vehicle into ghost car

### ISSUE THREAD

**Issue by dennrick** [qbcore-framework/qb-vehicleshop#231]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1.  Go to PDM and have someone else with you
2.  Purchase any vehicle
3.  Vehicle that spawns will not give keys and not be owned by the person who bought it and the garage app will show a different vehicle plate than what spawned

**Expected behavior**
Purchase vehicle and then spawn correct vehicle with same plate matching garage app

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Fresh build as of today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no - brought down a new build through txadmin to test this
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
This is only reprodueable with another play nearby.

**Comment by d-w00d** [comment]
Can confirm this is occurring with us  as well.

**Comment by Deadgaminglive** [comment]
something silmilar, we can purchase vehicles from lux and pdm but cannot store them in garages, have to dv them first then from impound they store fine, since core update (i updated vehicleshop at the same time)

**Comment by dennrick** [comment]
fixed with latest updates to core/vehicleshop
