### ISSUE TITLE
[BUG] Dont get keys for car if someone is nearby in poly zone

### ISSUE THREAD

**Issue by ArcadiaMatrix** [qbcore-framework/qb-vehicleshop#234]
So i have updated to the newest version of qb-vehicleshop and qb-vehiclekeys 

when you buy a car alone if no one else is around you will get the keys no issues 

but if you buy a car in pdm for example and someone else is in the show room you will spawn outside in the car but wont have keys 

To Reproduce issue:

have two people in the pdm showroom buy a car and you wont get keys, but if you go back into pdm and have the other person leave pdm and you rebuy a car it works just fine!

**Comment by GhzGarage** [comment]
Update the events and callbacks in qb-core for server vehicle spawning. This does work fine
