### ISSUE TITLE
[database and spawned vehicle have different plate ] 

### ISSUE THREAD

**Issue by Nerfednijt** [qbcore-framework/qb-vehicleshop#236]
**Describe the bug**
This bug happends sometimes , for some People in my server the buying car / test driving car works fine, for some people if they test drive the car spawns outside but you don't get the keys , for some People when they buy a car , it spawns outside , doesnt give then keys and the plate from the spawned vehicle doesnt match the plate it entered into the database 

**To Reproduce**
1. Go to to the shop and buy a car 

**Expected behavior**
The car will Spawn outside you will not get the keys and the plate wont match the one entered into the database ( for some People ) 

**Questions (please complete the following information):**
 - When you last updated: after first getting the issue ( 2 days ago ) 

**Additional context**
This was tested on the most recent version of the script

**Comment by Nerfednijt** [comment]
@GhzGarage  i assume this one is fixed aswell with the qb-core update ?

**Comment by GhzGarage** [comment]
Yes

**Comment by Wafflzdev** [comment]
@GhzGarage Does it require a full reinstall of QBCore or just the qb-core folder?
