### ISSUE TITLE
[BUG] Player does not spawn into vehicle / vehicle does not spawn after purchase or finance

### ISSUE THREAD

**Issue by AtlCanadianGG** [qbcore-framework/qb-vehicleshop#238]
Hi guys,

Latest installation of QB Vehicle Shop brought a new bug. The player does not teleport into the vehicle and the vehicle does not spawn after purchase or finance.

This is on a clean install (for testing purposes) and happens to all players. No client or server sided errors are popping up, either.

**Comment by JustGeezyGames** [comment]
Do you have the new spawnvehicle callbacks added to qb-core. I believe it's in qb-core/server/events.lua

**Comment by AtlCanadianGG** [comment]
> Do you have the new spawnvehicle callbacks added to qb-core. I believe it's in qb-core/server/events.lua

No, I wasn't aware those changes existed. 

Can you add them here and the line they're supposed to go? I'll add them in tonight and re test.

**Comment by JustGeezyGames** [comment]
> > Do you have the new spawnvehicle callbacks added to qb-core. I believe it's in qb-core/server/events.lua
> 
> No, I wasn't aware those changes existed.
> 
> Can you add them here and the line they're supposed to go? I'll add them in tonight and re test.

Check this link. Should have all the info you need. They did do some changes to it just the other day, so you might want to take a look at those too 

https://github.com/qbcore-framework/qb-core/commit/81ffd872319d2eb8e496c3b3faaf37e791912c84
