### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Helpme45879** [qbcore-framework/qb-vehicleshop#239]
So im trying to add a car sale point in the PD i have done the poly and put it in the shop config yet still dont work is there something im missing please help

**Comment by Helpme45879** [comment]
aint no vids on it or anything

**Comment by ProjectSting** [comment]
its not workin

**Comment by Blooper-bloop** [comment]
> So im trying to add a car sale point in the PD i have done the poly and put it in the shop config yet still dont work is there something im missing please help

Please go to the discord and open a post in Fivem Support :)
