### ISSUE TITLE
[BUG] Finance not taking payments from players, cars are getting deleted / repo

### ISSUE THREAD

**Issue by AtlCanadianGG** [qbcore-framework/qb-vehicleshop#241]
As the title says, people financing cars with plenty of money - payments are not leaving the bank, and the cars are vanishing / getting deleted or repo'd

**Comment by d-w00d** [comment]
Yes I can confirm this is an error as well and have had this happen to players within our server.

**Comment by Blooper-bloop** [comment]
> As the title says, people financing cars with plenty of money - payments are not leaving the bank, and the cars are vanishing / getting deleted or repo'd @AtlCanadianGG 

I can not reproduce this error could you show me or explain to me a bit more

**Comment by d-w00d** [comment]
So I have a server with average pop of 40 - 45 a night. This bug will not allow auto payments, or if a player even makes a payment by default before the repo time is up it still gets taken regardless. This is even on a fresh build. It could take a few days for this to happen. My only guess is to have a server with active players with this going on and see how many have this bug. I just know actively now that I had at least 6 players have this exact issue. Just from what I've been reported and what we've seen its just a fly by deal. No F8 Errors, no known issues showing.

**Comment by Blooper-bloop** [comment]
> So I have a server with average pop of 40 - 45 a night. This bug will not allow auto payments, or if a player even makes a payment by default before the repo time is up it still gets taken regardless. This is even on a fresh build. It could take a few days for this to happen. My only guess is to have a server with active players with this going on and see how many have this bug. I just know actively now that I had at least 6 players have this exact issue. Just from what I've been reported and what we've seen its just a fly by deal. No F8 Errors, no known issues showing.

Is everything up to date ? cause if not please update it all @d-w00d

**Comment by d-w00d** [comment]
> > So I have a server with average pop of 40 - 45 a night. This bug will not allow auto payments, or if a player even makes a payment by default before the repo time is up it still gets taken regardless. This is even on a fresh build. It could take a few days for this to happen. My only guess is to have a server with active players with this going on and see how many have this bug. I just know actively now that I had at least 6 players have this exact issue. Just from what I've been reported and what we've seen its just a fly by deal. No F8 Errors, no known issues showing.
> 
> Is everything up to date ? cause if not please update it all @d-w00d

Being updated? The most recent update is for "ES" and I don't use ES its EN. Of course, everything is up to day. But not with the new inventory changes as we won't be doing that update for a LONNNGGGG time till its fixed.

**Comment by Blooper-bloop** [comment]
> > > So I have a server with average pop of 40 - 45 a night. This bug will not allow auto payments, or if a player even makes a payment by default before the repo time is up it still gets taken regardless. This is even on a fresh build. It could take a few days for this to happen. My only guess is to have a server with active players with this going on and see how many have this bug. I just know actively now that I had at least 6 players have this exact issue. Just from what I've been reported and what we've seen its just a fly by deal. No F8 Errors, no known issues showing.
> > 
> > 
> > Is everything up to date ? cause if not please update it all @d-w00d
> 
> Being updated? The most recent update is for "ES" and I don't use ES its EN. Of course, everything is up to day. But not with the new inventory changes as we won't be doing that update for a LONNNGGGG time till its fixed.

Are you guys getting errors ? and im going to need some more information how many people is this happening to ? @d-w00d

**Comment by shox92** [comment]
Hey on my server I got the following Error Server Side

![Screenshot_116](https://user-images.githubusercontent.com/8252729/187623505-b416d1b0-0379-4023-97c0-70e2c3303b47.png)

**Comment by shox92** [comment]
Hey i sorted out my Issue
