### ISSUE TITLE
[BUG] Attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by fappyfeet** [qbcore-framework/qb-vehicleshop#243]
![image](https://user-images.githubusercontent.com/111238758/185715529-47edc693-7b53-4578-929a-6b8f1afe1f69.png)

I thought this was something to do with my files, but I have re-downloaded the whole QBcore-framework and same error. 

**To Reproduce**
Test drive a vehicle, car type doesn't matter I think. Then after a test drive, the error usually pops ups.

**Expected behavior**
 When the error pops up, the vehicle menu does not pop up / vehicle header. But.. there have been instances where the error pops up 
 and I can still test drive the vehicle. + Random NPC cars may spawn inside the shop, which is a bug in it's self I think.

![image](https://user-images.githubusercontent.com/111238758/185718997-13831c90-f563-4b15-bd5e-911e77c132f6.png)

 - When you last updated:
 Reinstalled everything (8/19/2022)
 Game Build = 2372
 
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 Not any that I have added. But qb-target is there originally.
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 No.

**Snippets**
**client.lua**
![image](https://user-images.githubusercontent.com/111238758/185719137-7b97b455-54d3-44d5-9f72-681edddfd390.png)

**ComboZone.lua**
![image](https://user-images.githubusercontent.com/111238758/185719323-ce662bda-030f-4d73-812c-7629b37f6ab1.png)

If more info is needed, I will try my best. Thank you

**Comment by All-Love2022** [comment]
This it still happening as well after the new update 12 hours ago with line 181

**Comment by Blooper-bloop** [comment]
> ![image](https://user-images.githubusercontent.com/111238758/185715529-47edc693-7b53-4578-929a-6b8f1afe1f69.png)
> 
> I thought this was something to do with my files, but I have re-downloaded the whole QBcore-framework and same error.
> 
> **To Reproduce** Test drive a vehicle, car type doesn't matter I think. Then after a test drive, the error usually pops ups.
> 
> **Expected behavior** When the error pops up, the vehicle menu does not pop up / vehicle header. But.. there have been instances where the error pops up and I can still test drive the vehicle. + Random NPC cars may spawn inside the shop, which is a bug in it's self I think.
> 
> ![image](https://user-images.githubusercontent.com/111238758/185718997-13831c90-f563-4b15-bd5e-911e77c132f6.png)
> 
> * When you last updated:
>   Reinstalled everything (8/19/2022)
>   Game Build = 2372
> * Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
>   Not any that I have added. But qb-target is there originally.
> * Have you renamed `qb-` to something custom? [e.g. yes/no]
>   No.
> 
> **Snippets** **client.lua** ![image](https://user-images.githubusercontent.com/111238758/185719137-7b97b455-54d3-44d5-9f72-681edddfd390.png)
> 
> **ComboZone.lua** ![image](https://user-images.githubusercontent.com/111238758/185719323-ce662bda-030f-4d73-812c-7629b37f6ab1.png)
> 
> If more info is needed, I will try my best. Thank you

Hello What you need to do is update everything and then let me know if it fixes it @fappyfeet
