### ISSUE TITLE
[BUG] Target

### ISSUE THREAD

**Issue by YvaneOficial** [qbcore-framework/qb-vehicleshop#245]
target no work

**Comment by Blooper-bloop** [comment]
> target no work

Im going to need more information then that bud any errors or what ? @YvaneOficial

**Comment by YvaneOficial** [comment]
no have erros, simply now the target to buy the vehicles does not appear

**Comment by Blooper-bloop** [comment]
> SCRIPT ERROR: @qb-vehicleshop/client.lua:196: attempt to call a nil value (global 'getShopInsideOf') ref (@qb-vehicleshop/client.lua:196) CheckOptions (@qb-target/init.lua:820) SetupOptions (@qb-target/client.lua:171) CheckEntity (@qb-target/client.lua:196) ref (@qb-target/client.lua:291)

Your vehicle shop up to date and what were you doing to get this error ? @YvaneOficial

**Comment by YvaneOficial** [comment]
use the target on cars .. 
but it does not work ..
old version works

**Comment by YvaneOficial** [comment]
> > ERRO DE SCRIPT: @qb-vehicleshop/client.lua:196: tentativa de chamar um valor nil (global 'getShopInsideOf') ref (@qb-vehicleshop/client.lua:196) CheckOptions (@qb-target/init.lua: 820) SetupOptions (@qb-target/client.lua:171) CheckEntity (@qb-target/client.lua:196) ref (@qb-target/client.lua:291)
> 
> Sua loja de veículos em dia e o que você estava fazendo para obter esse erro?@YvaneOficial

I try to select the eye and the eye does not appear

**Comment by YvaneOficial** [comment]
SCRIPT ERROR: @qb-vehicleshop/client.lua:181: attempt to index a nil value (field '?')
 onPointInOutCb (@qb-vehicleshop/client.lua:181)
 (@PolyZone/ComboZone.lua:272)

**Comment by YvaneOficial** [comment]
Apparently I figured out what's going on.
You cannot be inside the stand when the server starts..
I came to the street when I came back the target already works ..
But now there's another problem, I can't test drive or buy it..
says it was purchased but the vehicle does not appear

**Comment by YvaneOficial** [comment]
the cars when they are bought will stop at impound.. I have now come to the database

**Comment by OMikkel** [comment]
> But now there's another problem, I can't test drive or buy it..
says it was purchased but the vehicle does not appear
same thing with the test driver..
starts counting the time and the vehicle does not appear

You probably need the callback from `qb-core/server/events.lua` called [`QBCore:Server:SpawnVehicle`](https://github.com/qbcore-framework/qb-core/blob/main/server/events.lua#L211)
It appears multiple times in the `qb-vehicleshop/client.lua` file and is essential for spawning cars, I noticed I needed the callback when I tried to update `qb-vehicleshop`
https://github.com/qbcore-framework/qb-vehicleshop/blob/e67d1fe2cc777c60be54c694f295d0d3e80b1adb/client.lua#L419
https://github.com/qbcore-framework/qb-vehicleshop/blob/e67d1fe2cc777c60be54c694f295d0d3e80b1adb/client.lua#L443
https://github.com/qbcore-framework/qb-vehicleshop/blob/e67d1fe2cc777c60be54c694f295d0d3e80b1adb/client.lua#L619
