### ISSUE TITLE
I do not know?

### ISSUE THREAD

**Issue by HorizonGamings** [qbcore-framework/qb-vehicleshop#246]
![image](https://user-images.githubusercontent.com/101951820/187799525-87f63028-01c7-46a0-b092-2d1b2daae790.png)
![image](https://user-images.githubusercontent.com/101951820/187799581-82acdbbb-dfd0-4a66-9db0-49c605369c5e.png)
![image](https://user-images.githubusercontent.com/101951820/187799622-07775feb-a622-46ad-bfdb-63d1c9d6f230.png)
I do not know how to fix them I do not understand :c

**Comment by Blooper-bloop** [comment]
> ![image](https://user-images.githubusercontent.com/101951820/187799525-87f63028-01c7-46a0-b092-2d1b2daae790.png) ![image](https://user-images.githubusercontent.com/101951820/187799581-82acdbbb-dfd0-4a66-9db0-49c605369c5e.png) ![image](https://user-images.githubusercontent.com/101951820/187799622-07775feb-a622-46ad-bfdb-63d1c9d6f230.png) I do not know how to fix them I do not understand :c

Is your vehicle shop up to date ? @HorizonGamings

**Comment by SmithyPD** [comment]
did you make the polyzones for your shops? or is it standard locations?

**Comment by OMikkel** [comment]
Make sure the file `config.lua` is referenced in the shared_scripts in fxmanifest.lua
https://github.com/qbcore-framework/qb-vehicleshop/blob/main/fxmanifest.lua#L8
If not, it wont know about the Config table and result in that error
