### ISSUE TITLE
I have a error in qb vehicleshop when i change vehicles

### ISSUE THREAD

**Issue by Smokezz6969** [qbcore-framework/qb-vehicleshop#249]
![image](https://user-images.githubusercontent.com/99103156/188515281-ef29fa79-d5d4-4011-a417-46a8562f9366.png)

**Comment by Smokezz6969** [comment]
Yeah i have the newest qb and when i change vehicles and stuff

**Comment by OMikkel** [comment]
When did you last update? 
It seems a change was made to the file to fix an error similar to this, check out this commit https://github.com/qbcore-framework/qb-vehicleshop/commit/612a13873e5e960260ed74edc22a74cb0003eed6

I just cloned the repo and I am not getting this error, you might consider updating again :)
