### ISSUE TITLE
Cars not allowing to buy or change after first use

### ISSUE THREAD

**Issue by Fear6682** [qbcore-framework/qb-vehicleshop#254]
When you approach a car in my vehicle shop it says you can buy it and change it. If you move away and come back to the car it doesn't show a menu that allows you to buy, view or change the car. 

I get this error in F8:
script:qb-vehicleshop SCRIPT ERROR: @qb-vehicleshop/client/main.lua:190: attempt to index a nil value (field '?')
script:qb-vehicleshop > fn (@qb-vehicleshop/client/main.lua:190)

Please report back if you know the issue

**Comment by OMikkel** [comment]
It seems like you are running an old version of the resource `qb-vehicleshop`.

If you take a look at the repo, the file `qb-vehicleshop/client/main.lua` does not exist. 
You should try updating to the latest version, but remember to backup your files :)

**Comment by Blooper-bloop** [comment]
> When you approach a car in my vehicle shop it says you can buy it and change it. If you move away and come back to the car it doesn't show a menu that allows you to buy, view or change the car.
> 
> I get this error in F8: script:qb-vehicleshop SCRIPT ERROR: @qb-vehicleshop/client/main.lua:190: attempt to index a nil value (field '?') script:qb-vehicleshop > fn (@qb-vehicleshop/client/main.lua:190)
> 
> Please report back if you know the issue

Is it all fixed after what OMikkel Told you to do or dose it still not work ?

**Comment by Fear6682** [comment]
I cant update it because some of my scripts don't support oxmysql and its fixed but some cars break it for some reason. It's deal-able

**Comment by Blooper-bloop** [comment]
> I cant update it because some of my scripts don't support oxmysql and its fixed but some cars break it for some reason. It's deal-able

Then your most likely using an outdated version of vehicle shop @Fear6682

**Comment by j4kubk0cz** [comment]
> > I cant update it because some of my scripts don't support oxmysql and its fixed but some cars break it for some reason. It's deal-able
> 
> Then your most likely using an outdated version of vehicle shop @Fear6682

Where i can find the newest one?

**Comment by OMikkel** [comment]
Tit clone the repo or download it as a zip
