### ISSUE TITLE
Script Error, refrains from buying vehicles.

### ISSUE THREAD

**Issue by PeEcEeChIP** [qbcore-framework/qb-vehicleshop#26]
Script Error @qb-vehicleshop/client/main.lua:190: attempt to index a nil value (field '?')

Refrains from being able to buy vehicle's due to that error.

**Comment by PeEcEeChIP** [comment]
@GhzGarage I will mention this, it'll work once, but once someone buys a vehicle, it just stops working completely until a server restart is initiated.

**Comment by GhzGarage** [comment]
Tested and working properly
