### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ondrapd** [qbcore-framework/qb-vehicleshop#267]
**Describe the bug**
When I try to buy a car, it doesn’t give me the car keys so I can’t put it to the garage because it says that I don’t own the car, but in database ‘player vehicles’ it says that I own that vehicle , is there anything I could do?

**Questions (please complete the following information):**
 - When you last updated: yesterday
 - Are you using custom resource? Qb-target
 - Have you renamed `qb-` to something custom? No

**Comment by singh-manavv** [comment]
Make sure you have the latest version of qb-vehicleshop and qb-vehiclekeys . Also make sure qb-vehiclekeys is running .
