### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BobyTheDev** [qbcore-framework/qb-vehicleshop#268]
**Describe the bug**
Dealership gets stuck at certain car and then when you switch the vehicles change but the selected car doesnt

**To Reproduce**
1. Go to the dealership and then start switching thru cars and then this error happens

**Expected behavior**
To work properly

**Screenshots**
![image](https://user-images.githubusercontent.com/18469253/201428454-5f384782-96e2-436f-9bd8-6c1f2e1a10df.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 3 days ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] qb-target
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by DopeLovingHippy** [comment]
having the same errors ATM .... using qb-target haven't renamed anything (seems to be on free use shop i added) was wondering if it might be from mojito garage script  ??? [](url)
![1](https://user-images.githubusercontent.com/92433500/201780293-4a36c4a2-7785-4410-b56f-e079480ed99f.png)

**Comment by Z3rio** [comment]
Not recreatable / no error upon recreating.
