### ISSUE TITLE
[BUG] buying a car

### ISSUE THREAD

**Issue by Snili866** [qbcore-framework/qb-vehicleshop#271]
**Describe the bug**
when i buy a vehicle in pdm or deluxe vehicleshop the car does not spawn, i have to pick up the car from the impound lot

**To Reproduce**
1. Go to Pdm or Luxary vehicleshop
2. Click on vehicle and choose a car u want  2 buy
3. car will not spawn when u press buy. and u have to go to the impoundlot to get the car
4. See error ... no error comes up 

**Expected behavior**
  the car should spawn when u buy it
**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: few days ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by SKITTLE6969** [comment]
what's your fuel resource?

**Comment by Snili866** [comment]
im using ps-fuel

**Comment by SKITTLE6969** [comment]
have you adjusted your vehicleshop client side to ps-fuel?? ctrl+f and replace LegacyFuel with ps-fuel

**Comment by Soexclusive** [comment]
I started having that same issue after I downloaded the update about 2 weeks ago.
