### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by URGSky** [qbcore-framework/qb-vehicleshop#272]
**Describe the bug**
When I try to open any vehicle's options in the dealership, nothing happens, and I get an error in my F8 logs saying

`SCRIPT ERROR: @qb-vehicleshop/client.lua:97: attempt to index a nil value (field 'Vehicles')`
`getVehBrand(@qb-vehicleshop/client.lua:97`
`fn(qb-vehicleshop/client.lua:225)`

**Questions (please complete the following information):**
 - When you last updated: **A few hours ago**
 - Are you using custom resource? **No**
 - Have you renamed `qb-` to something custom? **No**

**Comment by Isolated94** [comment]
Same problem. Hoping for a fix

**Comment by r0adra93** [comment]
fix your vehicles.lua

**Comment by URGSky** [comment]
> fix your vehicles.lua

i did, but it keeps on failing. so technically i didnt

**Comment by Z3rio** [comment]
Invalid `shared/vehicles.lua`
Not an issue
