### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Killer233** [qbcore-framework/qb-vehicleshop#273]
when u change the car spots for gabz PDM the script breaks can we have a better update thats not the default please and thank you

**Comment by dmat1uk** [comment]
add this to you config.lua, i found the original polyzone didn't work with gabz map and when walking to one of the cars outside of the original polyzone it would break the scipt and ping an aerror in the console.

['Zone'] = {
            ['Shape'] = {
            vector2(-52.17264175415, -1078.341796875),
            vector2(-36.285980224609, -1084.6597900391),
            vector2(-25.360885620117, -1088.0903320312),
            vector2(-29.692399978638, -1098.6796875),
            vector2(-32.869251251221, -1108.7313232422),
            vector2(-47.286182403564, -1103.5101318359),
            vector2(-59.517723083496, -1098.9451904297),
            vector2(-56.312019348145, -1089.9029541016)

            },
            ['minZ'] = 25.0, 
            ['maxZ'] = 28.0, 
            ['size'] = 2.75 
        },

**Comment by Z3rio** [comment]
Not an issue. Just incorrect config.
