### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brandon1808** [qbcore-framework/qb-vehicleshop#274]
**Describe the bug**

When I add one of my custom cars into the vehicleshop. I don't change the name of the vehicle. It stay the same name of the vehicle that was there before changing the car. 

![Screenshot 2022-12-03 080233](https://user-images.githubusercontent.com/100901261/205450178-21c5b91c-ea3a-4b5d-b068-0cd13d5142ca.png)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]  just did a refresh of the scrpit 
 - Are you using custom resource? which ones? [NO ]
 - Have you renamed `qb-` to something custom? [ no] 

**Additional context**

**Comment by r0adra93** [comment]
you messed up your insertion into the vehicles.lua file. 
I will not include everything in the table but these 3 things must match and you must include the back tick around the spawn code in the hash. ` not a single quote or double quote ' or "
{vehicle spawn] = {
model = "vehicle spawn"
hash = `vehicle spawn` 
}
