### ISSUE TITLE
[BUG] Can't switch cars in the vehicleshop

### ISSUE THREAD

**Issue by URGSky** [qbcore-framework/qb-vehicleshop#278]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to PDM'
2. Step beside a car
3. Click on Vehicle Options'
4. See error in F8

**Expected behavior**
It should open the vehicle options menu where you can finance, buy or swap the vehicle if you'd like

**Screenshots**
![image](https://user-images.githubusercontent.com/78031510/207683182-6211ce48-7ad0-4a7d-aac1-2e9310f04a5a.png)

**Questions (please complete the following information):**
 - When you last updated: A few hours ago
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Comment by guap0035** [comment]
did you ever fix this?

**Comment by URGSky** [comment]
> did you ever fix this?

I did! All I did was encode it in UTF-8 and checked for some things I didn’t fill in so for example, there was several vehicles in the `qb-core` resource (in the shared folder where theres a file called `qb-vehicles`) that were missing some fields, had **several** syntax errors and some fields were misspelled for example `[caetgory] = 'coupes'`. To find all of these errors, if you haven’t already, install the Lua extension in your VSC. That helped me find all of the syntax errors.

Once I fixed all of that, I updated `qb-vehicleshop`, `qb-vehiclekeys`, `qb-garages`, `qb-vehiclesales` & `qb-inventory`. After that, everything was working as it should be. If you need anymore help, don’t be afraid to reply to this comment
