### ISSUE TITLE
Coords are not loading proper

### ISSUE THREAD

**Issue by OfficialRDB** [qbcore-framework/qb-vehicleshop#28]
Can anyone tell me if this is a script problem or just the MLO ?
After I restart the source it works fine. I got the coords by sitting in a car and put it on the right spot.

IDK if thats the right way to do it.
Maybe a start order issue, I did try to load the MLO first then the script and vice versa.

In my eyes the script doesn't load the coords proper.

Preview
https://streamable.com/rw7x7g

**Comment by GhzGarage** [comment]
Try lowering your Z

**Comment by OfficialRDB** [comment]
> 
> 
> Try lowering your Z

Ok that works.

If i add the category like for example:
`["Categories"] = {
            ["custom"]  = "Custom Imports",
        },`
Do i need to add that category at the bottom too, at QB.Classes ?

**Comment by Bigbearbeasttv** [comment]
It does not need to be in classes. 

"EDIT: Also not getting the car menu at the last car infront of the window"

I did confirm that it is not recognizing the last car that gets added to the showroom. Fresh install
