### ISSUE TITLE
[BUG] Missing interior for luxury dealership?

### ISSUE THREAD

**Issue by garagevive** [qbcore-framework/qb-vehicleshop#282]
I am at the spawn point for the luxury dealer:

        ['Job'] = 'cardealer', -- Name of job or none
        ['ShopLabel'] = 'Luxury Vehicle Shop',
        ['showBlip'] = true, -- true or false
        ['blipSprite'] = 326, -- Blip sprite
        ['blipColor'] = 3, -- Blip color
        ['TestDriveTimeLimit'] = 0.5,
        ['Location'] = vector3(-1255.6, -361.16, 36.91),

However, there is no enterable interior. It is inside the "Pump & Run Gym" - I see cars spawned inside.

Is there an MLO I need to install? I did some searching but feel like I am missing something as I don't see others mentioning this issue?

![image](https://user-images.githubusercontent.com/25409166/209710985-ee9901aa-594f-4edf-b59d-ccdc03f49918.png)

![image](https://user-images.githubusercontent.com/25409166/209711059-1e2afc5c-fb79-43ab-bb89-7551d95410c4.png)

![image](https://user-images.githubusercontent.com/25409166/209711127-64dd941c-09d0-43a2-988e-6c9fbfeea799.png)

**Comment by garagevive** [comment]
After loading an MLO for "Pump & Run" I can go inside and see the vehicles. Obviously this MLO is not conducive to selling cars but can confirm that I can enter the building. Otherwise, without this MLO I fall through the world in this location.

![image](https://user-images.githubusercontent.com/25409166/209711831-b97834f2-cc7c-49d6-a299-d9325e7021fd.png)

I am assuming there must be a car dealership MLO at this location I am missing?

Any help would be appreciated.

**Comment by troubleNZ** [comment]
you're looking for this: https://github.com/qbcore-framework/dealer_map

**Comment by garagevive** [comment]
Thanks so much!
