### ISSUE TITLE
Shop hangs when changing vehicles

### ISSUE THREAD

**Issue by Orion13622** [qbcore-framework/qb-vehicleshop#29]
New to Qb-core, but noticed that when the player changes the selected car in the dealership to a different model, the system will hang at trying to render in the model.  No errors displayed on the FiveM console.  Not sure why this is happening, but may need checked into.

Aside, great job on creating a much more reliable framework than ESX.

**Comment by EvilGnome93** [comment]
Got the same issue here :/

**Comment by EvilGnome93** [comment]
> New to Qb-core, but noticed that when the player changes the selected car in the dealership to a different model, the system will hang at trying to render in the model. No errors displayed on the FiveM console. Not sure why this is happening, but may need checked into.
> 
> Aside, great job on creating a much more reliable framework than ESX.

I found it :) you need to put a line in your config file.
You can find this in the core/shared.lue at the cars section

**Comment by Orion13622** [comment]
What line needs to be entered into the shared.lua file to prevent this
issue from happening?

Many thanks

**Comment by EvilGnome93** [comment]
Do u use txadmin?

**Comment by Orion13622** [comment]
Yes, I do.

**Comment by EvilGnome93** [comment]
Open it l, go to settings
Click  FXServer 
At additionele arguments fill in
+Set sv_enforceGameBuild 2189

**Comment by Orion13622** [comment]
Thought that was for just using the Casino, I did notice that qb-blackjack does not load, error states not all items available to get it to load.  I'll give that a go.

Would really be looking into adding a blackjack table for the playerbase, but looks complicated to get set up.

**Comment by Orion13622** [comment]
Thank you for your help on this.  I'll test it this afternoon and let you know if this resolves the issue.

**Comment by GhzGarage** [comment]
discord.gg/qbcore for support on this
