### ISSUE TITLE
How add vehicle distance for shop?

### ISSUE THREAD

**Issue by Rykamishlava** [qbcore-framework/qb-vehicleshop#32]
Hello guys, can u help for add a fonction to load only vehicle in the shop with a distance like "if dist = 4 , load vehicle" on the map, thank you bro, im so bad :/ 

like renzu shop, he load model only in a distance

**Comment by LifeStyleRolePlay** [comment]
If you are looking for support please join the QBCore discord and ask for help in one of their 10 support channels!

**Comment by GhzGarage** [comment]
discord.gg/qbcore
