### ISSUE TITLE
adding custom vehicle and categories to the shop

### ISSUE THREAD

**Issue by Armmm17** [qbcore-framework/qb-vehicleshop#34]
hi, anyone who can tell me how to add custom vehicle to the shop, for wxample i added some mercedes vehicle and i want that i can buy it in the shop

**Comment by LifeStyleRolePlay** [comment]
This is for issues only please. If you would like help with getting this sorted please visit the QBCore discord and use one of the 10 support channels for help!

**Comment by Armmm17** [comment]
plssss
its a issue

**Comment by GhzGarage** [comment]
discord.gg/qbcore
