### ISSUE TITLE
model spawning both locations

### ISSUE THREAD

**Issue by Sinistermind81** [qbcore-framework/qb-vehicleshop#36]
Make 2 dealerships, pdm[1] and luxury[2] when vehicle is changed to a different vehicle in menu, in positioned [1] at pdm, the car model changes in both pdm[1] and luxury[2] and same goes if you change the vehicle in luxury.

**Comment by roobr** [comment]
Look at https://github.com/qbcore-framework/qb-vehicleshop/pull/37

This should fix the issue you are having @Sinistermind81

**Comment by GhzGarage** [comment]
Fixed
