### ISSUE TITLE
Buying cars doesn't put me as owner

### ISSUE THREAD

**Issue by lordtopcat** [qbcore-framework/qb-vehicleshop#40]
I'm testing buying vehicles, and it doesn't put me as the owner:

![image](https://user-images.githubusercontent.com/6878216/139512900-2f058fbe-520c-4506-a8a1-7ea556fa08d6.png)

In the database, it goes down with the correct citizen ID, but not the correct name - and it is saying nobody owns this vehicle when trying to put it in a garage.

![image](https://user-images.githubusercontent.com/6878216/139512932-dc297a31-ede5-482e-bfb9-ff7cc2b9a9c5.png)

Every purchase puts a random name as the owner

![image](https://user-images.githubusercontent.com/6878216/139513065-2344b76e-3a28-4cbf-a9e6-23fe2090d14f.png)

And yet, when I go to vehicles on my phone app, it shows them in there:
![image](https://user-images.githubusercontent.com/6878216/139513100-b24bacc7-55a5-4c52-ade0-fbec8377d0f5.png)

**Comment by GhzGarage** [comment]
I think it's because your plate is only generating 6 letter/number combo and not 8

**Comment by lordtopcat** [comment]
Ahh yes, I reverted back to 8 characters and it's working now. Such an odd occurrence though, is that to be expected? Would love to have only 6 characters as that's how many we have in NZ...but can deal with 8 for now :)

**Comment by GhzGarage** [comment]
I’m looking into it
