### ISSUE TITLE
Using Cardealer Job shows message to all players

### ISSUE THREAD

**Issue by bakerzone** [qbcore-framework/qb-vehicleshop#43]
Bug.

If the Cardealer opens up a vehicle to put up for sale, everyone in the city has the exact same prompt for finance/change/buy shown to them no matter what the distance is.

We have tried being anywhere within the city and the same is seen.

The user that is in PDM might be looking at another vehicle and this is the one shown to everyone.

Selecting each option throws an error in client/469 attempt to index a nil value (    for k,v in pairs(Config.Shops[ClosestShop]['Categories']) do)

**Comment by bakerzone** [comment]
edit:
If a person is in the shop and the job is set to cardealer then they are show the prompt for all sales even to anyone else, no matter where they are in the city.

If they don't enter the shop then they aren't shown the prompts.

**Comment by GhzGarage** [comment]
Should be fixed

**Comment by bakerzone** [comment]
Thanks, works a treat...

Thanks again
