### ISSUE TITLE
Bug while more then 1 finance vehicle

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-vehicleshop#49]
tested with fresh install today

![Capture](https://user-images.githubusercontent.com/55808925/140296091-78e6f7f6-718a-4c5f-8dc7-ea4156dfc496.PNG)

problem causing time  =  while i have more then 1 finance vehicle

**Comment by ARSSANTO** [comment]
after few test its only happening when i have more then 1 financed vehicle

**Comment by zeemkarry** [comment]
I also have the same problem

**Comment by ARSSANTO** [comment]
updated vehicle shop yester day the issue still there some how
