### ISSUE TITLE
Dont start

### ISSUE THREAD

**Issue by RedEvilPPTT** [qbcore-framework/qb-vehicleshop#55]
hello I'm having problems with the car store I try to give start only that gives error that I can not do anythin
![error](https://user-images.githubusercontent.com/63155736/140648705-7af28f50-cc7e-4a05-9890-c13fbf201491.png)
g

**Comment by JensJFiveM** [comment]
ARHHH I got that as well and it dosnt work at all, idk what to do tbh

**Comment by DanteRedrum** [comment]
the script starts for me then tosses that error. it works but I'm also wondering how to fix this one. If I find an answer I'll post it here.
