### ISSUE TITLE
Luxuryshop without job requirements bug.

### ISSUE THREAD

**Issue by vulthrax** [qbcore-framework/qb-vehicleshop#56]
Hi, IF you change the luxury vehicleshop to none for job requirement in the config. Then the luxury vehicleshop isn't working as it has to be. 

Some examples: When joining server the car menu wont let you choose an option when opening in the luxury vehicleshop. IF you then visit the regular vehicleshop and go back to the luxury it works kinda, but buggy as hell. Wrong labeled car names but the changing and buying works sometimes  .

**Comment by MrRaposoo** [comment]
Yes But if you restart the server and if you spawn away of the vehicle shop the script works...
