### ISSUE TITLE
SCRIPT ERROR: @qb-vehicleshop/server/server.lua:11: attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by kalinpetrof** [qbcore-framework/qb-vehicleshop#6]
When i try to buy a vehicle in my console get this error :/
SCRIPT ERROR: @qb-vehicleshop/server/server.lua:11: attempt to index a nil value (local 'xPlayer')

**Comment by qbcore-framework** [comment]
Join the discord for support
