### ISSUE TITLE
Fails to start: QBCore not found

### ISSUE THREAD

**Issue by AceScottie** [qbcore-framework/qb-vehicleshop#61]
Can anyone help with this?
QBCore is enabled and started before qb-vehicleshop so not sure why im getting this error.
All dependencies have being met.
```
[    c-scripting-core] Creating script environments for qb-vehicleshop
[script:qb-vehiclesho] Error loading script server/main.lua in resource qb-vehicleshop: @qb-vehicleshop/server/main.lua:124: attempt to index a nil value (global 'QBCore')
[script:qb-vehiclesho] stack traceback:
[script:qb-vehiclesho] 	@qb-vehicleshop/server/main.lua:124: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
```
Log attached:

[fxserver_1636856222.log](https://github.com/qbcore-framework/qb-vehicleshop/files/7533076/fxserver_1636856222.log)

**Comment by DanteRedrum** [comment]
Add the following to the top of the qb-vehicleshop/server/main.lua

local QBCore = exports['qb-core']:GetCoreObject()

This is what fixed it for me.
