### ISSUE TITLE
Veh shop player owner issue.

### ISSUE THREAD

**Issue by BizkitCrackers** [qbcore-framework/qb-vehicleshop#68]
Hi,

I'd like some help with an issue I've got, when I am the 'cardealer' job I can see the 'Vehicle Options' appear however when I select it to try and sell to another player nothing else happens at all.
Seems like the player owned job isnt working for me.
Any suggestions?
[qb-vehicleshop-main.zip](https://github.com/qbcore-framework/qb-vehicleshop/files/7610664/qb-vehicleshop-main.zip)

**Comment by BizkitCrackers** [comment]
Ive seen this issue posted previously but cant see how it was resolved though

**Comment by Gainsfromgaming** [comment]
It has not been resolved as of yet it seems
