### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Squizy1722** [qbcore-framework/qb-vehicleshop#72]
I have change the positions of the cars to custom vehicleshop and now I can't buy vehicle or swap vehicle I have error
![862a4b28751b1c624434a79fbe31907a](https://user-images.githubusercontent.com/86523689/143852450-2437560e-88f5-4c93-8d6b-f7f8db624f82.png)

**Comment by Jarrad12** [comment]
yeah its a known issue with the new vehicleshop i think we need to wait for the qb devs to update the script

**Comment by ikrazy99** [comment]
Having the same issue, I thought it was me doing something wrong…. I was gonna go crazy. I created another shop at the police station, so cops could buy cars faster…. I got the menu to pop up but you can’t buy anything.

**Comment by Jarrad12** [comment]
yeah its the same with me i got the menu to show but when i click on it to get to the categories it disappears

**Comment by ikrazy99** [comment]
I've managed to get the options to pop up but it just prints out errors.. that shouldn't be given.

**Comment by OlliePugh** [comment]
Not had a proper look into it but have you added some logic surrounding a new Polyzone being created in your new area?

if you look below, for each shop you have to create a polyzone, if we look at pdmthis is the following approach: 

```
local pdm = PolyZone:Create({
    vector2(-56.727394104004, -1086.2325439453),
    vector2(-60.612808227539, -1096.7795410156),
    vector2(-58.26834487915, -1100.572265625),
    vector2(-35.927803039551, -1109.0034179688),
    vector2(-34.427627563477, -1108.5111083984),
    vector2(-32.02657699585, -1101.5877685547),
    vector2(-33.342102050781, -1101.0377197266),
    vector2(-31.292987823486, -1095.3717041016)
  }, {
    name="pdm",
    minZ = 25.0,
    maxZ = 28.0
})
```

Then a callback is attached to a user entering that zone with the following: 

```
	pdm:onPlayerInOut(function(isPointInside)
    if isPointInside then
        ClosestShop = 'pdm'
        inPDM = true
        CreateThread(function()
            while inPDM do
                setClosestShowroomVehicle()
                vehicleMenu = {
                    {
                        isMenuHeader = true,
                        header = getVehBrand():upper().. ' '..getVehName():upper().. ' - $' ..getVehPrice(),
                    },
                    {
                        header = 'Test Drive',
                        txt = 'Test drive currently selected vehicle',
                        params = {
                            event = 'qb-vehicleshop:client:TestDrive',
                        }
                    },
                    {
                        header = "Buy Vehicle",
                        txt = 'Purchase currently selected vehicle',
                        params = {
                            isServer = true,
                            event = 'qb-vehicleshop:server:buyShowroomVehicle',
                            args = {
                                buyVehicle = Config.Shops[ClosestShop]["ShowroomVehicles"][ClosestVehicle].chosenVehicle
                            }
                        }
                    },
                    {
                        header = 'Finance Vehicle',
                        txt = 'Finance currently selected vehicle',
                        params = {
                            event = 'qb-vehicleshop:client:openFinance',
                            args = {
                                price = getVehPrice(),
                                buyVehicle = Config.Shops[ClosestShop]["ShowroomVehicles"][ClosestVehicle].chosenVehicle
                            }
                        }
                    },
                    {
                        header = 'Swap Vehicle',
                        txt = 'Change currently selected vehicle',
                        params = {
                            event = 'qb-vehicleshop:client:vehCategories',
                        }
                    },
                }
                Wait(1000)
            end
        end)
    else
        inPDM = false
        ClosestShop = nil
    end
end)
```

If the user wasn't in one of these zones then they wont be able to trigger the buy vehicle event etc. This could be fixed by including this dynamically by looking at the shops listed in config.

If I find some time I will have a go at this, but thought I would give my take on it incase anyone else fancies a go :)

**Comment by ikrazy99** [comment]
I have tried this, I think maybe I don't know how to use the poly zone creator properly. I was just doing /pzcreate poly I believe and just putting points on the vehicle, I have also tried to make a box around the vehicles but no luck, just an empty menu.
