### ISSUE TITLE
Luxury Shop only sells pfister comet

### ISSUE THREAD

**Issue by vulthrax** [qbcore-framework/qb-vehicleshop#76]
Hi,

I'm using latest qb-core and latest script of the qb-vehicleshop. Only thing i changed is added the bugatti in the shared.lua to get it to spawn in a luxury Shop. Everything else is as provided on github latest versions. 

So my problem:  When i'm a Cardealer in the Luxury vehicleshop and i try to swap a car it swaps but only at one place. The other places in the shop are useless. Then for the spot that works and is able to change the car, it swaps the car to the desired car but for some odd reason the title keeps displaying pfister comet. I allready checked the shared.lua doesnt mention this car in the luxuryshop. So whatever i try to swap the car to i keep selling a pfister comet if i continue and sell it even when the car in shop displayed isnt the pfister comet. 

Streamable for reference https://streamable.com/auvyfd

**Comment by kokorog** [comment]
+1
