### ISSUE TITLE
How to remove or add different vehicles

### ISSUE THREAD

**Issue by Robinerino** [qbcore-framework/qb-vehicleshop#84]
The shop automatically comes with weaponized cars like the burrito custom and the caracara with a machinegun. Both in the database and everywhere in the vehicleshop plugin i can't find a single list of vehicles for me to remove and add.

On top of that, if i add custom cars to my server, i need to be able to add the modelname in the list somewhere. BUT WHERE!?
i can't find it. maybe im overlooking it but i would appreciate some help

**Comment by RustinCassiem** [comment]
@Robinerino 

All vehicles that you want to remove or add can be found in your qb-core/shared.lua 

you can add your custom cars to the shared.lua just makes sure to add the new category to the qb-vehicles and shared.lue in qb-core

this is also where you can modify practically anything 

found the answer today while looking for something else and thought I'd share it with everyone here
