### ISSUE TITLE
Newest update thinks I'm closer to luxury when I'm in PDM

### ISSUE THREAD

**Issue by HavocHN** [qbcore-framework/qb-vehicleshop#87]
![image](https://user-images.githubusercontent.com/31086023/146773400-a293b398-9ea9-4323-9571-fe134fb6fc34.png)

Newest update thinks I'm closer to luxury when I'm in PDM.

**Comment by OlliePugh** [comment]
I witnessed this issue when restarting inside of a shop.

If I recall correctly, leaving the shop. Restarting the shop and restarting the plugin should resolve it

**Comment by OlliePugh** [comment]
Did you also update your config to correspond with the new config fields?

**Comment by OlliePugh** [comment]
I am really struggling to recreate this bug. If you could message me on discord to help me reproduce it that would be amazing. Puggy#7595

**Comment by OlliePugh** [comment]
There also seems to be an issue with the most recent update with qb-input that is effecting vehicle shop. Most likely related to that. Revert back to a previous version of qb-input to fix.
