### ISSUE TITLE
Swipe through PDM cars and go to luxury to get access to the luxury menu

### ISSUE THREAD

**Issue by zeemkarry** [qbcore-framework/qb-vehicleshop#88]
PDM Job = none
Luxury Job = cardealer

situation: after swiping through the cars in PDM, to go Luxury shop. Now you have full access to Luxury menu and can even buy the cars.

**Comment by OlliePugh** [comment]
I believe a recent update to qb-input has been causing issues with this resource. Are you on the most recent verision of qb-input? If thats the case you may want to go back a version
