### ISSUE TITLE
SCRIPT ERROR: @qb-vehicleshop/server.lua:44: attempt to perform arithmetic on a table value (local 'playTime')

### ISSUE THREAD

**Issue by MaximusR9** [qbcore-framework/qb-vehicleshop#91]
`[script:qb-vehiclesho] SCRIPT ERROR: @qb-vehicleshop/server.lua:44: attempt to perform arithmetic on a table value (local 'playTime')
[script:qb-vehiclesho] > safeCallback (@oxmysql/oxmysql.js:20087)
[script:qb-vehiclesho] > <unknown> (@oxmysql/oxmysql.js:20094)
[script:qb-vehiclesho] > runMicrotasks (<anonymous>:0)
[script:qb-vehiclesho] > processTicksAndRejections (node:internal/process/task_queues:96)`

https://github.com/qbcore-framework/qb-vehicleshop/blob/eae1d49c01f60aebc825cc9a030484b6a17eb348/server.lua#L44

**Comment by bigramb0** [comment]
Why are you closing unsolved issues?
