### ISSUE TITLE
Financing vehicles breaks UI

### ISSUE THREAD

**Issue by TKFALLENONE** [qbcore-framework/qb-vehicleshop#95]
When trying to finalize the purchase for finance on a vehicle at either shop location it breaks the UI and makes the player unable to move. When relogged the UI Menus for vehicles are entirely gone and don't come back. Server specs are on the latest artifacts and set on game build 2372 with all of the proper dependencies.

**Comment by GhzGarage** [comment]
Errors?

**Comment by TKFALLENONE** [comment]
None in the F8 Console. I did see a QB-Input error once but I don't think it was related as it hasn't come back since. I forgot to mention OneSync Infinity is enabled.

**Comment by GhzGarage** [comment]
Alright i'll look into it

**Comment by TKFALLENONE** [comment]
I have seen one other person mention of this a few days ago on the FiveM forums. Exact same issue, but other than that I haven't seen anything or any solutions on how to fix it.

**Comment by ImpulseFPS** [comment]
is the ui stuck on the screen or not?

**Comment by TKFALLENONE** [comment]
No the ui disappears after putting in the down payment and payment term. It leaves the mouse control active but you can't escape out of it or click on anything. It just glitches out and makes it necessary to relog

**Comment by ImpulseFPS** [comment]
did you by any chance change the folder names of the qb-menu and qb-input if so you can change things in .js files or change the folder name back to qb-menu and qb-input

**Comment by TKFALLENONE** [comment]
I didn't, they're named qb-input and qb-menu

**Comment by MaximusR9** [comment]
> None in the F8 Console. I did see a QB-Input error once but I don't think it was related as it hasn't come back since. I forgot to mention OneSync Infinity is enabled.

are there any errors on the server console?

**Comment by chunce01** [comment]
I am running into this as well, ended up removing the finance option for my server. It disconnects your mouse from the game like qb-input is having a failure. Looking through server logs nothing is registered in Live console or f8 when this occurs.

**Comment by TKFALLENONE** [comment]
No errors in the server console or the F8 console.

**Comment by GhzGarage** [comment]
Try re-downloading qb-input and try again

**Comment by TKFALLENONE** [comment]
That worked! Thank you
