### ISSUE TITLE
selling cars glitch

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-vehicleshop#98]
if you sell a person a car he left the pdm or luxury it keeps that as closest person and cardealer can sell cars but no car spawn but goes to 1st buyer garage so basically its keeping the 1st person who bought the car

**Comment by ItsAegeus** [comment]
having report of this happing on my server as well.

**Comment by GhzGarage** [comment]
Will be changing this method to ID instead of closest
